### ISSUE TITLE
readme 有单词是不是写错了

### ISSUE THREAD

**Issue by weichangdong** [git-hulk/routines#2]
```
Routines was a fixed number thread pool to process the user task, and it would respawn a corresponding new thread when 

panic. It supports the sync process mode that would wait for the response, as well as the **sync** mode, which would not 

wait for the response. The most commonly used scenario was to control the max concurrency when processing jobs.
```

是不是 应该是 **async**

**Comment by weichangdong** [comment]
和
 ```github.com/panjf2000/ants``` 
这个的功能 是不是差不多?

**Comment by git-hulk** [comment]
> ```
> Routines was a fixed number thread pool to process the user task, and it would respawn a corresponding new thread when 
> 
> panic. It supports the sync process mode that would wait for the response, as well as the **sync** mode, which would not 
> 
> wait for the response. The most commonly used scenario was to control the max concurrency when processing jobs.
> ```
> 
> 是不是 应该是 **async**

是的，good catch

**Comment by git-hulk** [comment]
> 和
> `github.com/panjf2000/ants`
> 这个的功能 是不是差不多?

不太确定 ants 是不是固定的 pool size
